log_levels:
  level_0: true
  level_1: true
  level_2: true
  level_3: true
  level_4: true
  level_5: true
  level_6: true
  level_7: true
ignored_channels: {  }
format: '[!level] [!type] [!ip] [uid:!uid] [!request_uri] [!referer] !message'
